pipeline {
    agent any
    tools {
        maven 'Maven'
        
    }
    stages {
       
        

        stage ('Build') {
            steps {
                echo "Building" 
            }
        }
            stage ('Test') {
                steps {
                    echo "Testing"
                }
            }
      
    }
    
}
